sudo: false
language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
  - develop
  - generate-deployable-config
cache:
  directories:
  - node_modules
  - bower_components
before_script:
- npm install -g bower
- npm install -g gulp
- npm install -g istanbul
- npm install -g codeclimate-test-reporter
- npm install
- bower install
script:
- gulp test
after_success:
- cp coverage/*/lcov.info .
- codeclimate-test-reporter < lcov.info
# generate deployable configuration 
- sed -e "s/<API_KEY>/test/" -e "s/<BASE_URL>/test/" < src/app/app.deploy.config.js > src/app/app.config.js
- gulp build
deploy:
  provider: s3
  bucket: develop.flash-app.stsilabs
  skip_cleanup: true
  local_dir: dist
  on:
    branch: develop
notifications:
  slack:
    secure:
