sudo: false
language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
  - develop
  - stage
cache:
  directories:
  - node_modules
  - bower_components
before_script:
- npm install -g bower
- npm install -g gulp
- npm install -g istanbul
- npm install -g codeclimate-test-reporter
- npm install
- bower install
script:
- gulp test
after_success:
- cp coverage/*/lcov.info .
- codeclimate-test-reporter < lcov.info
# generate deployable configuration
- sed -e "s/<API_KEY>/$DEVELOP_API_KEY/" -e "s/<BASE_URL>/$DEVELOP_FLASH_API_ENDPOINT/" < src/app/app.deploy.config.js > src/app/app.config.js
- cat src/app/app.config.js
- gulp build
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: stage.flash-app.stsilabs
  skip_cleanup: true
  local_dir: dist
  on:
    branch: stage
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: develop.flash-app.stsilabs
  skip_cleanup: true
  local_dir: dist
  on:
    branch: develop
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: prod.flash-app.stsilabs
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
notifications:
  slack:
    secure:
